version: "3.7"

services:
  postgresql:
    image: postgres:16.1
    ports:
      - 5432:5432
    volumes:
      - workflow-postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=camunda
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER}
      interval: 5s
      timeout: 5s
      retries: 5

  camunda:
    image: backend:1.0.0-SNAPSHOT
    ports:
      - 8080:8080
    depends_on:
      - postgresql
      - redis-service
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1000M
        reservations:
          cpus: '0.5'
          memory: 500M

  redis-service:
    image: redis:7-alpine
    ports:
      - 6379:6379

volumes:
  workflow-postgresql-data: