apiVersion: apps/v1
kind: Deployment
metadata:
   name: redis-deployment
   namespace: camunda
spec:
   replicas: 1
   selector:
      matchLabels:
         app: redis
   minReadySeconds: 60
   template:
      metadata:
         labels:
            app: redis
      spec:
         containers:
         - name: redis
           image: redis:7-alpine
           ports:
           - containerPort: 6379
           livenessProbe:
            exec:
               command:
               - sh
               - -c
               - redis-cli -a {{ .Values.app.env.REDIS_PASSWORD }} ping
            initialDelaySeconds: 10
            timeoutSeconds: 5
           resources:
             limits:
               cpu: 250m
               memory: 256Mi
             requests:
               cpu: 250m
               memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
   name: redis-service
   namespace: camunda
   labels:
      app: redis
spec:
   type: ClusterIP
   ports: 
   - port: 6379
     targetPort: 6379
   selector:
      app: redis